---
- name: Скачивание дистрибутива kibana
  ansible.builtin.get_url:
    url: https://mirror.yandex.ru/mirrors/elastic/8/pool/main/k/kibana/kibana-8.17.0-amd64.deb
    dest: /tmp/kibana-8.17.0-amd64.deb
    mode: 0777

- name: Установка дистрибутива kibana
  ansible.builtin.apt:
    deb: /tmp/kibana-8.17.0-amd64.deb

- name: Удаление .deb пакета kibana
  ansible.builtin.file:
    path: kibana-8.17.0-amd64.deb
    state: absent

- name: Конфигурация файла настроек kibana
  ansible.builtin.template:
    src: kibana.j2
    dest: /etc/kibana/kibana.yml
    owner: root
    group: kibana
    mode: 0660

- name: enable and restart services
  ansible.builtin.service:
    name: kibana
    enabled: yes
    state: restarted
  