---
- name: enable zabbix-agent
  ansible.builtin.service:
    name: zabbix-agent2
    enabled: yes

- name: restart zabbix-agent
  ansible.builtin.service:
    name: zabbix-agent2
    state: restarted
