---
kibana_host_address: kibana.ru-central1.internal:5601
elastic_host_address: elasticsearch.ru-central1.internal:9200
nginx_accesslog_path: /var/log/nginx/access.log
nginx_errorlog_path: /var/log/nginx/error.log
