- name: добавление репозиториев заббикс
  ansible.builtin.shell:
    echo "deb http://repo.zabbix.com/zabbix/7.0/ubuntu/ jammy main" | sudo tee /etc/apt/sources.list.d/zabbix.list

- name: update cache
  ansible.builtin.apt:
    update_cache: true

- name: install zabbix-agent
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present 
  loop:
    - zabbix-agent2
    - zabbix-agent2-plugin-*
  notify: enable zabbix-agent

- name: Copy configuration file
  ansible.builtin.template:
    src: zabbix_agent.j2
    dest: /etc/zabbix/zabbix_agent2.conf
    owner: root
    group: root
    mode: 0644
  notify: restart zabbix-agent
